window.DEFAULT_SPOTS = [
  {
    "id": "seed-001",
    "name": "白糸の滝",
    "genre": "自然・名勝",
    "area": "",
    "address": "静岡県富士宮市上井出273-1",
    "phone": "",
    "homepage": "",
    "description": "国の名勝および天然記念物。高さ20m・幅150mの崖から数百の滝が流れ落ちる。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 1,
    "active": true
  },
  {
    "id": "seed-002",
    "name": "音止の滝",
    "genre": "自然・名勝",
    "area": "",
    "address": "静岡県富士宮市上井出",
    "phone": "",
    "homepage": "",
    "description": "白糸の滝のすぐ近くにある迫力ある名瀑。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 2,
    "active": true
  },
  {
    "id": "seed-003",
    "name": "富士山本宮浅間大社",
    "genre": "神社・仏閣",
    "area": "",
    "address": "静岡県富士宮市宮町1-1",
    "phone": "",
    "homepage": "",
    "description": "全国に1,300以上ある浅間神社の総本宮。徳川家康造営の本殿でも知られる。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 3,
    "active": true
  },
  {
    "id": "seed-004",
    "name": "湧玉池",
    "genre": "自然・名勝",
    "area": "",
    "address": "静岡県富士宮市宮町1-1",
    "phone": "",
    "homepage": "",
    "description": "富士山の雪解け水が湧き出る国の特別天然記念物。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 4,
    "active": true
  },
  {
    "id": "seed-005",
    "name": "静岡県富士山世界遺産センター",
    "genre": "文化施設",
    "area": "",
    "address": "静岡県富士宮市宮町5-12",
    "phone": "",
    "homepage": "",
    "description": "富士山の歴史や文化、美しさを学べる施設。美しい木造建築とらせんスロープが特徴。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 5,
    "active": true
  },
  {
    "id": "seed-006",
    "name": "田貫湖",
    "genre": "自然・名勝",
    "area": "",
    "address": "静岡県富士宮市佐折",
    "phone": "",
    "homepage": "",
    "description": "湖面に映る逆さ富士やダイヤモンド富士で有名な景勝地。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 6,
    "active": true
  },
  {
    "id": "seed-007",
    "name": "朝霧高原",
    "genre": "自然・レジャー",
    "area": "",
    "address": "静岡県富士宮市根原周辺",
    "phone": "",
    "homepage": "",
    "description": "富士山を望む大牧草地。キャンプや牧場などのレジャーが点在する。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 7,
    "active": true
  },
  {
    "id": "seed-008",
    "name": "まかいの牧場",
    "genre": "牧場・体験",
    "area": "",
    "address": "静岡県富士宮市内野1327-1",
    "phone": "",
    "homepage": "",
    "description": "動物とのふれあいやグルメが楽しめる体験型牧場。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 8,
    "active": true
  },
  {
    "id": "seed-009",
    "name": "富士ミルクランド",
    "genre": "牧場・体験",
    "area": "",
    "address": "静岡県富士宮市上井出3690",
    "phone": "",
    "homepage": "",
    "description": "動物とのふれあいや自家製乳製品が人気の牧場。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 9,
    "active": true
  },
  {
    "id": "seed-010",
    "name": "ふもとっぱら",
    "genre": "キャンプ場",
    "area": "",
    "address": "静岡県富士宮市麓156",
    "phone": "",
    "homepage": "",
    "description": "雄大な富士山を望む、全国的に人気の広大なキャンプ場。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 10,
    "active": true
  },
  {
    "id": "seed-011",
    "name": "陣馬の滝",
    "genre": "自然・名勝",
    "area": "",
    "address": "静岡県富士宮市猪之頭",
    "phone": "",
    "homepage": "",
    "description": "穏やかな森と豊かな湧水に囲まれた美しい滝。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 11,
    "active": true
  },
  {
    "id": "seed-012",
    "name": "奇石博物館",
    "genre": "博物館",
    "area": "",
    "address": "静岡県富士宮市山宮3670",
    "phone": "",
    "homepage": "",
    "description": "世界中から集まったユニークな石を展示する博物館。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 12,
    "active": true
  },
  {
    "id": "seed-013",
    "name": "狩宿の下馬桜",
    "genre": "史跡・自然",
    "area": "",
    "address": "静岡県富士宮市狩宿98-1",
    "phone": "",
    "homepage": "",
    "description": "日本五大桜の一つ。国指定特別天然記念物のヤマザクラ。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 13,
    "active": true
  },
  {
    "id": "seed-014",
    "name": "人穴富士講遺跡",
    "genre": "史跡",
    "area": "",
    "address": "静岡県富士宮市人穴",
    "phone": "",
    "homepage": "",
    "description": "富士講の信仰対象となった溶岩洞穴と多数の碑塔が残る。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 14,
    "active": true
  },
  {
    "id": "seed-015",
    "name": "山宮浅間神社",
    "genre": "神社・仏閣",
    "area": "",
    "address": "静岡県富士宮市山宮474",
    "phone": "",
    "homepage": "",
    "description": "本殿を持たず、直接富士山を遥拝する古代祭祀の形を伝える神社。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 15,
    "active": true
  },
  {
    "id": "seed-016",
    "name": "道の駅 朝霧高原",
    "genre": "道の駅",
    "area": "",
    "address": "静岡県富士宮市根原492-14",
    "phone": "",
    "homepage": "",
    "description": "富士山の絶景と地域の特産品・グルメが楽しめる道の駅。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 16,
    "active": true
  },
  {
    "id": "seed-017",
    "name": "道の駅 富士宮",
    "genre": "道の駅",
    "area": "",
    "address": "静岡県富士宮市田中町668",
    "phone": "",
    "homepage": "",
    "description": "富士宮やきそばなどのグルメや特産品が揃う拠点として登録されたスポット。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 17,
    "active": true
  },
  {
    "id": "seed-018",
    "name": "富嶽温泉 花の湯",
    "genre": "温浴施設",
    "area": "",
    "address": "静岡県富士宮市ひばりが丘805",
    "phone": "",
    "homepage": "",
    "description": "多彩なお風呂やサウナが楽しめる大型温浴・宿泊施設。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 18,
    "active": true
  },
  {
    "id": "seed-019",
    "name": "富士山天母の湯",
    "genre": "温浴施設",
    "area": "",
    "address": "静岡県富士宮市猪之頭",
    "phone": "",
    "homepage": "",
    "description": "富士山中腹にあり、眺望が魅力の市営日帰り温泉。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 19,
    "active": true
  },
  {
    "id": "seed-020",
    "name": "西山本門寺",
    "genre": "神社・仏閣",
    "area": "",
    "address": "静岡県富士宮市西山",
    "phone": "",
    "homepage": "",
    "description": "日蓮宗の古刹。信長公首塚や見事なイチョウがある。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 20,
    "active": true
  },
  {
    "id": "seed-021",
    "name": "柚野の里（郷土資料等）",
    "genre": "史跡・文化",
    "area": "",
    "address": "静岡県富士宮市内野・柚野地区",
    "phone": "",
    "homepage": "",
    "description": "里山の原風景が広がり、ホタルや史跡が点在する地域。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 21,
    "active": true
  },
  {
    "id": "seed-022",
    "name": "猪之頭公園",
    "genre": "公園",
    "area": "",
    "address": "静岡県富士宮市猪之頭",
    "phone": "",
    "homepage": "",
    "description": "富士山の湧水を利用した池があり、マス釣りなどが楽しめる。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 22,
    "active": true
  },
  {
    "id": "seed-023",
    "name": "もちだまき資料館",
    "genre": "博物館",
    "area": "",
    "address": "静岡県富士宮市長貫",
    "phone": "",
    "homepage": "",
    "description": "地域の歴史や文化を伝える資料館。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 23,
    "active": true
  },
  {
    "id": "seed-024",
    "name": "佐折の富士山ビューポイント",
    "genre": "自然・名勝",
    "area": "",
    "address": "静岡県富士宮市佐折",
    "phone": "",
    "homepage": "",
    "description": "田貫湖周辺の美しい富士山を眺められる撮影スポット。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 24,
    "active": true
  },
  {
    "id": "seed-025",
    "name": "県立朝霧野外活動センター",
    "genre": "レジャー",
    "area": "",
    "address": "静岡県富士宮市根原",
    "phone": "",
    "homepage": "",
    "description": "朝霧高原にある自然体験・研修施設。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 25,
    "active": true
  },
  {
    "id": "seed-026",
    "name": "富士山環境交流プラザ",
    "genre": "文化施設",
    "area": "",
    "address": "静岡県富士宮市北山",
    "phone": "",
    "homepage": "",
    "description": "富士山の環境保全や自然学習のための施設。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 26,
    "active": true
  },
  {
    "id": "seed-027",
    "name": "富士山神田川楽座",
    "genre": "観光拠点",
    "area": "",
    "address": "静岡県富士宮市淀師",
    "phone": "",
    "homepage": "",
    "description": "神田川沿いの観光・交流拠点として登録されたスポット。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 27,
    "active": true
  },
  {
    "id": "seed-028",
    "name": "富士宮市民プール",
    "genre": "レジャー",
    "area": "",
    "address": "静岡県富士宮市大岩",
    "phone": "",
    "homepage": "",
    "description": "夏季に多くの家族連れでにぎわう市民プール。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 28,
    "active": true
  },
  {
    "id": "seed-029",
    "name": "外神東公園",
    "genre": "公園",
    "area": "",
    "address": "静岡県富士宮市外神",
    "phone": "",
    "homepage": "",
    "description": "広場や遊具が整備された地域住民に親しまれる公園。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 29,
    "active": true
  },
  {
    "id": "seed-030",
    "name": "芝川図書館・周辺文化施設",
    "genre": "文化施設",
    "area": "",
    "address": "静岡県富士宮市羽鮒",
    "phone": "",
    "homepage": "",
    "description": "旧芝川町エリアの文化拠点。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 30,
    "active": true
  },
  {
    "id": "seed-031",
    "name": "内房の筍・里山エリア",
    "genre": "自然・グルメ",
    "area": "",
    "address": "静岡県富士宮市内房",
    "phone": "",
    "homepage": "",
    "description": "豊かな自然と特産のタケノコなどで知られる里山エリア。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 31,
    "active": true
  },
  {
    "id": "seed-032",
    "name": "稲子川温泉 ユー・トリオ",
    "genre": "温浴施設",
    "area": "",
    "address": "静岡県富士宮市羽鮒",
    "phone": "",
    "homepage": "",
    "description": "旧芝川エリアにある静かな温泉保養施設。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 32,
    "active": true
  },
  {
    "id": "seed-033",
    "name": "光厳寺",
    "genre": "神社・仏閣",
    "area": "",
    "address": "静岡県富士宮市山宮",
    "phone": "",
    "homepage": "",
    "description": "歴史ある静寂な寺院。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 33,
    "active": true
  },
  {
    "id": "seed-034",
    "name": "大カツラ（上井出の巨樹）",
    "genre": "自然・名勝",
    "area": "",
    "address": "静岡県富士宮市上井出",
    "phone": "",
    "homepage": "",
    "description": "地域の天然記念物として知られる巨樹。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 34,
    "active": true
  },
  {
    "id": "seed-035",
    "name": "富士眺望の湯 富士ぐりんぱ（近接・関連）",
    "genre": "レジャー",
    "area": "",
    "address": "静岡県富士宮市（裾野市境付近）",
    "phone": "",
    "homepage": "",
    "description": "富士山南西麓の近接レジャーエリアとして登録されたスポット。",
    "image_url": "",
    "lat": null,
    "lng": null,
    "sort_order": 35,
    "active": true
  }
];
